"""Aggregate reviewer A/B verdicts → agreement rates, list of disagreements (for adjudication), consensus file (adjudicated.jsonl), Table behavior.

Consensus rule: if A=B, take that value. For a disagreement, take the adjudicated value (reviewer C) from data/adjudication/<chunk>.jsonl if present; otherwise unresolved (None).
Outputs: data/agreement.json, data/disagreements.jsonl, data/adjudicated.jsonl, table_behavior.tex"""
import json, os, glob, collections, sys
HERE = os.path.dirname(os.path.abspath(__file__)); sys.path.insert(0, os.path.join(HERE, "..", "..", "common", "section3"))
import loaders as L
D = os.path.join(HERE, "data")
Q = ["q1_scan", "q2_prop", "q3_ungrounded", "q4_mag_rationale", "q5_causal_chain", "f_gt_considered", "m1_premature", "m2_self_contra", "m3_stop_after_commit"]
LABEL = {"q1_scan": "Examines anomalies of two or more candidates", "q2_prop": "Reasons about propagation across components",
         "q3_ungrounded": "Cites an observation absent from the input", "q4_mag_rationale": "Final decision rests on anomaly magnitude",
         "q5_causal_chain": "Final decision names a causal chain between components", "f_gt_considered": "GT component considered as a candidate",
         "m1_premature": "Commits to the largest anomaly before comparing alternatives", "m2_self_contra": "Own propagation/timing analysis points elsewhere",
         "m3_stop_after_commit": "Stops examining alternatives after committing"}
def load(rev):
    out = {}
    for p in sorted(glob.glob(os.path.join(D, "judge_outputs", rev, "*.jsonl"))):
        for l in open(p):
            l = l.strip()
            if not l: continue
            r = json.loads(l); out[r["job"]] = r
    return out
A, B = load("A"), load("B")
C = {}
for p in glob.glob(os.path.join(D, "adjudication", "*.jsonl")):
    for l in open(p):
        if l.strip(): r = json.loads(l); C[r["job"]] = r
jobs = sorted(set(A) & set(B)); won = {t["job"]: t["won"] for t in L.load_v4_trajectories()}
agree = {q: sum(1 for j in jobs if A[j][q] == B[j][q]) / max(1, len(jobs)) for q in Q}
dis = []; adj = []
for j in jobs:
    row = {"job": j, "won": won.get(j)}
    for q in Q:
        if A[j][q] == B[j][q]: row[q] = A[j][q]
        else:
            row[q] = C.get(j, {}).get(q); dis.append(dict(job=j, q=q, A=A[j][q], B=B[j][q], quoteA=A[j].get("quote"), quoteB=B[j].get("quote")))
    adj.append(row)
with open(os.path.join(D, "disagreements.jsonl"), "w") as f:
    for d in dis: f.write(json.dumps(d, ensure_ascii=False) + "\n")
with open(os.path.join(D, "adjudicated.jsonl"), "w") as f:
    for r in adj: f.write(json.dumps(r, ensure_ascii=False) + "\n")
def rate(rows, q):
    v = [r[q] for r in rows if r[q] in ("yes", "no")]; return (sum(1 for x in v if x == "yes") / len(v), len(v)) if v else (None, 0)
succ = [r for r in adj if r["won"]]; fail = [r for r in adj if not r["won"]]
table = {q: dict(label=LABEL[q], success=rate(succ, q), failure=rate(fail, q), all=rate(adj, q), agreement=agree[q]) for q in Q}
summary = dict(n_jobs=len(jobs), n_success=len(succ), n_failure=len(fail), n_disagreements=len(dis), n_unresolved=sum(1 for r in adj for q in Q if r[q] is None), table=table)
json.dump(summary, open(os.path.join(D, "agreement.json"), "w"), indent=1, ensure_ascii=False)
def pct(x): return "--" if x[0] is None else f"{100*x[0]:.0f}\\,\\%"
tex = ["% auto-generated by figures/section_3/behavior_judge/aggregate.py", "Question & Success & Failure & Agreement \\\\", "\\midrule"]
for q in ("q1_scan", "q2_prop", "q3_ungrounded", "q4_mag_rationale", "q5_causal_chain"):
    t = table[q]; tex.append(f"{t['label']} & {pct(t['success'])} & {pct(t['failure'])} & {100*t['agreement']:.0f}\\,\\% \\\\")
open(os.path.join(HERE, "table_behavior.tex"), "w").write("\n".join(tex) + "\n")
print(json.dumps(summary, indent=1, ensure_ascii=False))
